org: zipcase
app: zipcase

services:
    infra:
        path: infra

    ws:
        path: ws
        dependsOn:
            - infra

    app:
        path: app
        dependsOn:
            - infra
            - api
            - ws

    api:
        path: api
        dependsOn:
            - infra
